Updated and fixed project
liuznsn/boilerplate pull request #5
Opened 2018-10-25 19:24 UTC by Tawfikk

♻️ In this pull request i fixed constraints in the LoginViewController, which did't activate and so it's displayed incorrect! And little updated the TrendigViewController/ViewModel for my code style 😎

📷 Before fixed the constraints 
<img width="387" alt="screenshot 2018-10-25 at 22 19 28" src="https://user-images.githubusercontent.com/28268405/47524707-0bdbf200-d8a4-11e8-8371-3d8d90811702.png">

 🛠 and after
<img width="387" alt="screenshot 2018-10-25 at 22 21 27" src="https://user-images.githubusercontent.com/28268405/47524817-53627e00-d8a4-11e8-8ad2-b2b372df06ea.png">

2018-11-26 10:01 UTC, singhamit089 approved these changes

2018-11-26 10:07 UTC, singhamit089 requested changes
Hey why didn't you create a branch ?

2018-11-26 10:17 UTC, Tawfikk commented
🤷🏻‍♂️

2018-11-28 10:20 UTC, merged

2018-11-28 10:21 UTC, liuznsn commented
@singhamit089  Thanks.